# Generated by Django 5.2.4 on 2025-08-04 08:32

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title (5-100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator], verbose_name='Service Name')),
                ('description', models.TextField(help_text='Detailed service description (20-1000 characters)', max_length=1000, validators=[django.core.validators.MinLengthValidator(20)])),
                ('icon', models.CharField(default='fas fa-user-md', help_text='Font Awesome icon class', max_length=50)),
                ('image', models.ImageField(help_text='Service card image (recommended size: 600x400px)', upload_to=services.models.service_image_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='whether the service should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering field (higher numbers come first)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-order', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'), models.Index(fields=['order'], name='services_se_order_8a41e4_idx')],
            },
        ),
    ]
