# Generated by Django 5.2.4 on 2025-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated)', max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
    ]
